server:
  port : 8080
spring:
   cloud:
      stream:
         # define functions that will be used on bindings
         function:
            definition: AProcessor;BConsumer;StringConsumer
         # kafka is the message engine
         kafka:
            default:
               consumer:
                  startOffset: latest
            binder:
               brokers: localhost:29092
               replicationFactor: 1
         # define  bindings
         bindings:
            # syntax is: <function&ComponentName>-in-0 or <function&ComponentName>-in-0
            AProcessor-in-0:
               group: group5
               destination: queueA
            AProcessor-out-0:
               group: group5
               destination: queueB
            BConsumer-in-0:
               group: group5
               destination: queueB
            StringConsumer-in-0:
               group: group5
               destination: stringQ
            #define consumer group (spring.cloud.stream.bindings.<channel>.group=<name>)
