server:
   port : 8080
spring:
   cloud:
      stream:
         # kafka is the message engine
         kafka:
            default:
               consumer:
                  startOffset: latest
            binder:
               brokers: localhost:9092
               replicationFactor: 1
         # functional processing
         function:
            definition: AProcessor;BConsumer;StringConsumer;StringMultipleConsumer
         # define  bindings
         bindings:
            # syntax is: <function&ComponentName>-in-0 or <function&ComponentName>-in-0
            AProcessor-in-0:
               group: group5
               destination: queueA
            AProcessor-out-0:
               group: group5
               destination: queueB
            BConsumer-in-0:
               group: group5
               destination: queueB
            StringConsumer-in-0:
               group: group5
               destination: stringQ
            StringMultipleConsumer-in-0:
               group: group5
               #destination: stringMultipleQ.*
               destination: stringMultipleQ_1,stringMultipleQ_2
# for multi-server grouping, see:
# https://stackoverflow.com/questions/54850308/spring-cloud-stream-consumer-group-bound
